site_name: Calculator Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search

repo_url: https://github.com/seapagan/python-docs-with-mkdocs
repo_name: seapagan/python-docs-with-mkdocs

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
